Repository newrelic/gatsby-theme-newrelic, pull requests merged in 2020-07, with the labels that each got.

#35 Add the New Relic Logo component
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/src/components/NewRelicLogo.js
Labels: enhancement

#34 Typography styles
  packages/gatsby-theme-newrelic/gatsby-ssr.js
  packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js
  packages/gatsby-theme-newrelic/src/components/GlobalStyles.js
Labels: enhancement

#36 Fix failing action
  .github/workflows/pr_merged.yml
Labels: bug

#38 Add global header
  demo/gatsby-config.js
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/gatsby-node.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/package.json
  packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js
  packages/gatsby-theme-newrelic/src/components/ExternalLink.js
  packages/gatsby-theme-newrelic/src/components/FeatherSVG.js
  packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
  packages/gatsby-theme-newrelic/src/components/GlobalNavLink.js
  packages/gatsby-theme-newrelic/src/components/Icon.js
  packages/gatsby-theme-newrelic/src/components/NewRelicLogo.js
  packages/gatsby-theme-newrelic/src/icons/feather.js
  packages/gatsby-theme-newrelic/src/utils/constantize.js
  packages/gatsby-theme-newrelic/src/utils/transformKeys.js
  yarn.lock
Labels: enhancement

#42 Documentation for API and configuration
  README.md
Labels: documentation

#46 Search component
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/src/components/SearchInput.js
  packages/gatsby-theme-newrelic/src/icons/feather.js
Labels: enhancement

#44 Add <CodeBlock />
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/gatsby-node.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/package.json
  packages/gatsby-theme-newrelic/src/components/CodeBlock.js
  packages/gatsby-theme-newrelic/src/components/CodeEditor.js
  packages/gatsby-theme-newrelic/src/components/CodeHighlight.js
  packages/gatsby-theme-newrelic/src/components/MDXCodeBlock.js
  packages/gatsby-theme-newrelic/src/hooks/useClipboard.js
  packages/gatsby-theme-newrelic/src/hooks/useDeepMemo.js
  packages/gatsby-theme-newrelic/src/hooks/useFormattedCode.js
  packages/gatsby-theme-newrelic/src/hooks/useTimeout.js
  packages/gatsby-theme-newrelic/src/icons/feather.js
  packages/gatsby-theme-newrelic/src/utils/array.js
  packages/gatsby-theme-newrelic/src/utils/copyToClipboard.js
  packages/gatsby-theme-newrelic/src/utils/formatCode.js
  yarn.lock
Labels: enhancement

#45 Add <HamburgerMenu/> component
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/src/components/HamburgerMenu.js
Labels: enhancement

#47 Add <Surface /> component
  README.md
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/src/components/GlobalStyles.js
  packages/gatsby-theme-newrelic/src/components/Surface.js
Labels: enhancement

#49 Add keywords to package.json
  packages/gatsby-theme-newrelic/package.json
Labels: enhancement

#48 Add video component
  demo/src/pages/index.js
  packages/gatsby-theme-newrelic/index.js
  packages/gatsby-theme-newrelic/src/components/Video.js
Labels: enhancement

#50 Add all component and hook documentation
  README.md
  packages/gatsby-theme-newrelic/README.md
Labels: documentation

#52 Update GitHub token env var name
  .github/workflows/release.yml
Labels: bug

#54 Fix YouTube and Wistia video examples
  packages/gatsby-theme-newrelic/README.md
Labels: documentation

#57 Add dark mode box shadow
  packages/gatsby-theme-newrelic/src/components/Surface.js
Labels: enhancement
